version: '3.1'
services:
  mongo:
    container_name: bot_store_mongo_db
    image: mongo
    volumes:
      - /var/lib/mongodb/bot_store:/data/db
    expose:
      - ${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${EXTERNAL_DB_PORT}:${DB_PORT}"
    env_file:
      - ".env"

  bot:
    image: python:3.10-slim
    container_name: bot_store_bot
    env_file:
      - ".env"
    depends_on:
      - mongo
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python main.py"
# TODO бот запускать через dockerfile